- name: instalando pacotes debian
  apt:
    name: "{{item}}"
    state: present
  with_items:
      - apache2
  when: ansible_os_family == "Debian"

- name: verificando se o apache está habilitado
  service:
   name: "{{item}}"
   state: started
  with_items:
   - apache2
  when: ansible_osfamily == "Debian"





